apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: devops-prod
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: devops-prod
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
